import type { Metadata } from "next";
import "./globals.css";
import "@/css/main.css";
import {Footer, Loader} from "@/components";
import Provider from "./Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Provider>
          <Loader />
          {children}
          <Footer />
        </Provider>
          <div className="bg-image" style={{backgroundImage: "url(images/bg-dark.jpg)"}}></div>
      </body>
    </html>
  );
}
