import type { Metadata } from "next";
import "@/css/globals.css";
import "@/css/main.css";
import {Footer, Layout, Loader, Navigation} from "@/components";
import Provider from "./Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Provider>
          <Loader />
          <Layout>
            <Navigation />
            {children}

          </Layout>
          <Footer />
        </Provider>
          <div className="bg-image" style={{backgroundImage: "url(images/bg-dark.jpg)"}}></div>
      </body>
    </html>
  );
}
